CREATE TABLE mascota (
  id_mascota NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  id_Owner NUMBER(11) NOT NULL,
  nombre_Mascota VARCHAR2(255) NOT NULL,
  tipo_Mascota VARCHAR2(255) NOT NULL,
  raza_Mascota VARCHAR2(255) NOT NULL,
  CONSTRAINT mascota_pk PRIMARY KEY (id_mascota)
);

CREATE TABLE pet_owner (
  id_propietario NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  nombre_Propietario VARCHAR2(255) NOT NULL,
  apellido_Propietario VARCHAR2(255) NOT NULL,
  telefono_Propietario VARCHAR2(255) NOT NULL,
  CONSTRAINT pet_owner_pk PRIMARY KEY (id_propietario)
);


-- private int id;
--     private int idMascota;
--     private int precio;
--     private String nombre;
--     private String descripcion;
--     private String fecha;
--     private String ubicacion;
--     private String estado;


CREATE TABLE Concurso (
  id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  id_mascota NUMBER(11) NOT NULL,
  id_propietario NUMBER(11) NOT NULL,
  precio NUMBER(11) NOT NULL,
  nombre VARCHAR2(255) NOT NULL,
  descripcion VARCHAR2(255) NOT NULL,
  fecha VARCHAR2(255) NOT NULL,
  ubicacion VARCHAR2(255) NOT NULL,
  estado VARCHAR2(255) NOT NULL,
  CONSTRAINT Concursos_pk PRIMARY KEY (id)
);

drop table Concursos;
drop table mascota;
drop table pet_owner;
drop table viaje;
drop table conductor_transporte_mascota;

CREATE USER C##CONCURSO_MASCOTA IDENTIFIED BY concurso_123;

--grant privileges to the user for all tables and sequences
GRANT ALL PRIVILEGES ON C##CONCURSO_MASCOTA.mascota TO C##CONCURSO_MASCOTA;
GRANT ALL PRIVILEGES ON C##CONCURSO_MASCOTA.pet_owner TO C##CONCURSO_MASCOTA;

ALTER USER C##CONCURSO_MASCOTA QUOTA UNLIMITED ON USERS;

--grant privileges to the user for all tables and sequences
GRANT ALL PRIVILEGES ON C##CONCURSO_MASCOTA.mascota TO C##VIAJE_MASCOTA;
GRANT ALL PRIVILEGES ON C##CONCURSO_MASCOTA.pet_owner TO C##VIAJE_MASCOTA;
GRANT ALL PRIVILEGES ON C##CONCURSO_MASCOTA.Concursos TO C##VIAJE_MASCOTA;
GRANT CREATE SESSION TO C##CONCURSO_MASCOTA;
GRANT CREATE TABLE TO C##CONCURSO_MASCOTA;
GRANT CREATE SEQUENCE TO C##CONCURSO_MASCOTA;


truncate table viaje;