CREATE TABLE mascota (
  id_mascota NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  id_Owner NUMBER(11) NOT NULL,
  nombre_Mascota VARCHAR2(255) NOT NULL,
  tipo_Mascota VARCHAR2(255) NOT NULL,
  raza_Mascota VARCHAR2(255) NOT NULL,
  CONSTRAINT mascota_pk PRIMARY KEY (id_mascota)
);

CREATE TABLE pet_owner (
  id_propietario NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  nombre_Propietario VARCHAR2(255) NOT NULL,
  apellido_Propietario VARCHAR2(255) NOT NULL,
  telefono_Propietario VARCHAR2(255) NOT NULL,
  CONSTRAINT pet_owner_pk PRIMARY KEY (id_propietario)
);

CREATE TABLE viaje (
  id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  id_mascota NUMBER(11) NOT NULL,
  id_Conductor NUMBER(11) NOT NULL,
  fecha_Viaje DATE NOT NULL,
  hora_Viaje TIMESTAMP NOT NULL,
  LUGAR_RECOGIDA VARCHAR2(255) NOT NULL,
  lugar_destino VARCHAR2(255) NOT NULL,
  estado_Viaje VARCHAR2(255) NOT NULL,
  costo_Viaje NUMBER(10,2) NOT NULL,
  CONSTRAINT viaje_pk PRIMARY KEY (id)
);

CREATE TABLE conductor_transporte_mascota (
  id_conductor NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  nombre_Conductor VARCHAR2(255) NOT NULL,
  apellido_Conductor VARCHAR2(255) NOT NULL,
  telefono_Conductor VARCHAR2(255) NOT NULL,
  CONSTRAINT conductor_pk PRIMARY KEY (id_conductor)
);

drop table mascota;
drop table pet_owner;
drop table viaje;
drop table conductor_transporte_mascota;

--create a user with database access
CREATE USER TRAVEL_MASCOTA IDENTIFIED BY Test_prueba0000001000;

--Permisos para conectar y modificar , agregar y eliminar tablas
GRANT CREATE SESSION TO TRAVEL_MASCOTA;
GRANT CREATE TABLE TO TRAVEL_MASCOTA;
GRANT CREATE SEQUENCE TO TRAVEL_MASCOTA;


--grant privileges to the user for all tables and sequences
GRANT ALL PRIVILEGES ON TRAVEL_MASCOTA.mascota TO TRAVEL_MASCOTA;
GRANT ALL PRIVILEGES ON TRAVEL_MASCOTA.pet_owner TO TRAVEL_MASCOTA;

ALTER USER TRAVEL_MASCOTA QUOTA UNLIMITED ON USERS;

--grant privileges to the user for all tables and sequences
GRANT ALL PRIVILEGES ON C##TRAVEL_MASCOTA.mascota TO C##TRAVEL_MASCOTA;
GRANT ALL PRIVILEGES ON C##TRAVEL_MASCOTA.pet_owner TO C##TRAVEL_MASCOTA;
GRANT ALL PRIVILEGES ON C##TRAVEL_MASCOTA.viaje TO C##TRAVEL_MASCOTA;
GRANT ALL PRIVILEGES ON C##TRAVEL_MASCOTA.conductor_transporte_mascota TO C##TRAVEL_MASCOTA;
GRANT CREATE SESSION TO C##TRAVEL_MASCOTA;
GRANT CREATE TABLE TO C##TRAVEL_MASCOTA;
GRANT CREATE SEQUENCE TO C##TRAVEL_MASCOTA;


truncate table viaje;